# Generated by Django 5.2.8 on 2025-11-10 11:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.headline')),
                ('poll_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.poll_information')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'headline')},
            },
        ),
    ]
