# Generated by Django 5.2.8 on 2025-11-10 09:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=300)),
                ('headline-logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('headline-image', models.ImageField(blank=True, null=True, upload_to='header_image')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Poll_information',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=250)),
                ('sub_category', models.CharField(max_length=250)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('votes', models.IntegerField(default=0)),
                ('headline', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voting.headline')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('pub_date', models.DateField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_date', models.DateField(auto_now_add=True)),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.headline')),
                ('poll_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.poll_information')),
            ],
        ),
    ]
