# Generated by Django 5.2.6 on 2025-10-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='headline-image',
            field=models.ImageField(blank=True, null=True, upload_to='header_image'),
        ),
        migrations.AlterField(
            model_name='headline',
            name='headline-logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
