# Generated by Django 5.2.7 on 2025-11-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='option',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='poll_info',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='poll',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AddField(
            model_name='poll_information',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
