# Generated by Django 5.2.8 on 2025-12-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='allow_vote_changes',
            field=models.BooleanField(default=True),
        ),
    ]
