# Generated by Django 5.2.7 on 2025-10-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_headline_headline_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
