# Generated by Django 6.0 on 2025-12-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_headline_allow_vote_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='require_google_auth',
            field=models.BooleanField(default=False, help_text='Require Google OAuth authentication to vote'),
        ),
    ]
