# Generated by Django 5.2.8 on 2025-11-08 19:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_remove_vote_option_remove_poll_headline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('pub_date', models.DateField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_date', models.DateField(auto_now_add=True)),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.headline')),
                ('poll_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.poll_information')),
            ],
        ),
    ]
