# Generated by Django 5.2.7 on 2025-10-17 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_headline_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll_information',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='poll_information',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
