# Generated by Django 5.2.7 on 2025-10-22 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_poll_information_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll_information',
            name='headline',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='poll_information', to='voting.headline'),
        ),
        migrations.AlterField(
            model_name='poll_information',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
