# Generated by Django 5.2.7 on 2025-10-22 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_poll_information_headline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll_information',
            name='headline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poll_information', to='voting.headline'),
        ),
    ]
