# Generated by Django 5.2.7 on 2025-10-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_alter_poll_information_headline'),
    ]

    operations = [
    ]
