# Generated by Django 5.2.7 on 2025-10-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_auto_20251022_1211'),
    ]

    operations = [
    ]
