# Generated by Django 5.2.7 on 2025-10-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_alter_poll_information_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll_information',
            name='headline',
        ),
    ]
